version: '3'
services:
  web:
    image: webdevops/php-apache-dev
    ports:
      - 30000:80

  adminer:
    image: adminer
    ports:
      - 50000:80

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
